# Usa uma imagem base com o JDK 17
FROM openjdk:17-jdk-slim as builder

# Define o diretório de trabalho
WORKDIR /app

# Copia o Maven Wrapper e o pom.xml
COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .

# Executa o build para baixar as dependências
RUN ./mvnw dependency:go-offline

# Copia o código-fonte
COPY src src

# Empacota a aplicação em um JAR
RUN ./mvnw clean install -DskipTests

# Usa uma imagem mais leve para o ambiente de execução
FROM openjdk:17-jre-slim

# Define o diretório de trabalho
WORKDIR /app

# Copia o JAR do estágio de build
COPY --from=builder /app/target/*.jar ./app.jar

# Expõe a porta que a aplicação vai rodar
EXPOSE 8080

# Comando para rodar a aplicação
ENTRYPOINT ["java", "-jar", "app.jar"]